-- CoachOps — Supabase schema
-- Run this once in the Supabase SQL editor.
--
-- Note on `id`: every table uses `generated by default as identity`, NOT
-- `generated always`. The app is offline-first: Dexie assigns the primary key
-- locally and sync pushes that id so player_id/team_id/session_id references
-- stay valid across devices. Postgres rejects explicit ids on a GENERATED ALWAYS
-- column (error 428C9), which silently breaks every push.

-- The hierarchy is: coach (auth user) -> club -> age group (team) -> squad
-- and activity rows. Only `owner_id` is stored per row; club and group are
-- linked by foreign keys so a coach can run several clubs and several age
-- groups per club.

-- Coach profile (one row per coach; `id` is the coach's auth user id)
create table if not exists coach_profiles (
  id uuid primary key,
  full_name text,
  phone text,
  club_note text,
  created_at timestamptz default now()
);

-- Clubs
create table if not exists clubs (
  id bigint generated by default as identity primary key,
  name text not null,
  city text,
  created_at timestamptz default now()
);

-- Teams / age groups
create table if not exists teams (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  season text,
  club_id bigint references clubs(id) on delete set null,
  created_at timestamptz default now()
);

-- Players
create table if not exists players (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  full_name text not null,
  jersey_number int,
  position text,
  parent_phone text,
  status text default 'نشط',
  photo_url text,
  birth_date date
);

-- Training sessions
create table if not exists sessions (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  date date not null,
  type text default 'تدريب',
  location text,
  notes text,
  time text
);

-- Attendance
create table if not exists attendance (
  id bigint generated by default as identity primary key,
  session_id bigint references sessions(id) on delete cascade,
  player_id bigint references players(id) on delete cascade,
  status text not null,
  notes text
);

-- Lineups
create table if not exists lineups (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  formation text,
  opponent text,
  date date,
  venue text,
  captain_id bigint,
  slots jsonb default '[]'::jsonb,
  substitutes jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  goals_for int,
  goals_against int,
  scorers jsonb default '[]'::jsonb,
  mvp_id bigint
);

-- Subscriptions (cotisations)
create table if not exists cotisations (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  player_id bigint references players(id) on delete cascade,
  month text,
  season text,
  expected_amount numeric default 0,
  paid_amount numeric default 0,
  status text default 'unpaid',
  method text,
  receipt_number text,
  last_payment_date date,
  created_at timestamptz default now()
);

-- Expenses
create table if not exists expenses (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  category text,
  amount numeric default 0,
  description text,
  date date,
  created_at timestamptz default now()
);

-- Player evaluations
create table if not exists evaluations (
  id bigint generated by default as identity primary key,
  player_id bigint references players(id) on delete cascade,
  team_id bigint references teams(id) on delete cascade,
  date date,
  technique int,
  physique int,
  tactique int,
  mental int,
  notes text,
  created_at timestamptz default now()
);

-- Helpful indexes
create index if not exists idx_players_team on players(team_id);
create index if not exists idx_sessions_team on sessions(team_id);
create index if not exists idx_attendance_session on attendance(session_id);
create index if not exists idx_attendance_player on attendance(player_id);
create index if not exists idx_cotisations_team on cotisations(team_id);
create index if not exists idx_expenses_team on expenses(team_id);
create index if not exists idx_lineups_team on lineups(team_id);

-- `updated_at` columns: the client syncs with last-write-wins, comparing these
-- timestamps per row. Safe to run repeatedly.
alter table teams add column if not exists updated_at timestamptz;
alter table players add column if not exists updated_at timestamptz;
alter table sessions add column if not exists updated_at timestamptz;
alter table attendance add column if not exists updated_at timestamptz;
alter table lineups add column if not exists updated_at timestamptz;
alter table cotisations add column if not exists updated_at timestamptz;
alter table expenses add column if not exists updated_at timestamptz;
alter table evaluations add column if not exists updated_at timestamptz;
-- The club level of the hierarchy needs the same column: the sync engine stamps
-- and compares `updated_at` on every table it pushes, so a table missing it
-- fails the whole push with PGRST204.
alter table clubs add column if not exists updated_at timestamptz;
alter table coach_profiles add column if not exists updated_at timestamptz;

-- ============================================================================
-- Ownership + Row Level Security
-- ============================================================================
-- Every table carries `owner_id`, pointing at the coach (auth.users) who owns
-- the row. Policies below are scoped to the signed-in coach, so the anon key in
-- the client bundle can no longer read or write other people's data --
-- including parents' phone numbers and payment records.
--
-- Run this whole file once. It is safe to re-run EXCEPT for the final
-- `create policy` block (Postgres has no `create policy if not exists`), so on a
-- re-run either skip that block or drop the policies first.

alter table teams       enable row level security;
alter table players     enable row level security;
alter table sessions    enable row level security;
alter table attendance  enable row level security;
alter table lineups     enable row level security;
alter table cotisations enable row level security;
alter table expenses    enable row level security;
alter table evaluations enable row level security;
alter table clubs       enable row level security;
alter table coach_profiles enable row level security;

alter table teams       add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table players     add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table sessions    add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table attendance  add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table lineups     add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table cotisations add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table expenses    add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table evaluations add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table clubs       add column if not exists owner_id uuid references auth.users(id) on delete cascade;

-- `club_id` is new to `teams`. `create table if not exists teams (...)` is a
-- no-op on an existing database, so the column has to be added explicitly here
-- or the index below fails with `column "club_id" does not exist`.
alter table teams add column if not exists club_id bigint references clubs(id) on delete set null;

-- Default monthly subscription per age group (dirhams). A club may charge
-- younger players less, so this lives on the group rather than being global.
alter table teams add column if not exists monthly_fee numeric;

create index if not exists idx_teams_club on teams(club_id);

create index if not exists idx_teams_owner       on teams(owner_id);
create index if not exists idx_players_owner     on players(owner_id);
create index if not exists idx_sessions_owner    on sessions(owner_id);
create index if not exists idx_attendance_owner  on attendance(owner_id);
create index if not exists idx_lineups_owner     on lineups(owner_id);
create index if not exists idx_cotisations_owner on cotisations(owner_id);
create index if not exists idx_expenses_owner    on expenses(owner_id);
create index if not exists idx_evaluations_owner on evaluations(owner_id);
create index if not exists idx_clubs_owner       on clubs(owner_id);

-- Remove the wide-open policies from before auth was wired up. Under RLS these
-- were effectively "anyone with the anon key owns everything".
drop policy if exists "public read teams"       on teams;
drop policy if exists "public write teams"      on teams;
drop policy if exists "public read players"     on players;
drop policy if exists "public write players"    on players;
drop policy if exists "public read sessions"    on sessions;
drop policy if exists "public write sessions"   on sessions;
drop policy if exists "public read attendance"  on attendance;
drop policy if exists "public write attendance" on attendance;
drop policy if exists "public read lineups"     on lineups;
drop policy if exists "public write lineups"    on lineups;
drop policy if exists "public read cotisations" on cotisations;
drop policy if exists "public write cotisations" on cotisations;
drop policy if exists "public read expenses"    on expenses;
drop policy if exists "public write expenses"   on expenses;
drop policy if exists "public read evaluations" on evaluations;
drop policy if exists "public write evaluations" on evaluations;

-- Postgres has no `create policy if not exists`, so the coach-scoped policies
-- are dropped first too. That makes this file safe to re-run end to end.
drop policy if exists "own teams"         on teams;
drop policy if exists "own players"       on players;
drop policy if exists "own sessions"      on sessions;
drop policy if exists "own attendance"    on attendance;
drop policy if exists "own lineups"       on lineups;
drop policy if exists "own cotisations"   on cotisations;
drop policy if exists "own expenses"      on expenses;
drop policy if exists "own evaluations"   on evaluations;
drop policy if exists "own clubs"         on clubs;
drop policy if exists "own coach profile" on coach_profiles;

-- Coach-scoped access. `(select auth.uid())` is wrapped in a scalar subquery so
-- Postgres evaluates it once per statement rather than per row.
create policy "own teams"       on teams       for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "own players"     on players     for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "own sessions"    on sessions    for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "own attendance"  on attendance  for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "own lineups"     on lineups     for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "own cotisations" on cotisations for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "own expenses"    on expenses    for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "own evaluations" on evaluations for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "own clubs"       on clubs       for all using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
-- The coach profile is keyed by the auth user id itself, so the policy matches
-- on `id` rather than a separate owner_id column.
create policy "own coach profile" on coach_profiles for all using (id = (select auth.uid())) with check (id = (select auth.uid()));

-- ============================================================================
-- Legacy data migration (one-time, run AFTER creating your account)
-- ============================================================================
-- Any rows created before auth existed have owner_id = NULL and are therefore
-- invisible to every policy above. To adopt them into your account, sign in
-- through the app: the first sign-in claims unowned rows automatically.
-- Alternatively, run this manually with your own user id substituted:
--
--   update teams       set owner_id = '<your-auth-uid>' where owner_id is null;
--   update players     set owner_id = '<your-auth-uid>' where owner_id is null;
--   update sessions    set owner_id = '<your-auth-uid>' where owner_id is null;
--   update attendance  set owner_id = '<your-auth-uid>' where owner_id is null;
--   update lineups     set owner_id = '<your-auth-uid>' where owner_id is null;
--   update cotisations set owner_id = '<your-auth-uid>' where owner_id is null;
--   update expenses    set owner_id = '<your-auth-uid>' where owner_id is null;
--   update evaluations set owner_id = '<your-auth-uid>' where owner_id is null;

-- ============================================================================
-- MIGRATION: allow client-assigned ids (required for sync)
-- ============================================================================
-- If your tables were created before this fix they still use
-- `generated always as identity`, and every push fails with:
--   428C9 cannot insert a non-DEFAULT value into column "id"
--
-- Run this once in the SQL editor to relax them to BY DEFAULT, so Dexie's local
-- primary keys can be pushed while still allowing server-side inserts.
-- Dropping and re-adding the identity resets the sequence, so the setval calls
-- move each sequence past the current maximum id to avoid collisions.
alter table teams       alter column id drop identity;
alter table teams       alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('teams', 'id'), greatest(coalesce((select max(id) from teams), 0) + 1, 1), false);

alter table players     alter column id drop identity;
alter table players     alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('players', 'id'), greatest(coalesce((select max(id) from players), 0) + 1, 1), false);

alter table sessions    alter column id drop identity;
alter table sessions    alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('sessions', 'id'), greatest(coalesce((select max(id) from sessions), 0) + 1, 1), false);

alter table attendance  alter column id drop identity;
alter table attendance  alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('attendance', 'id'), greatest(coalesce((select max(id) from attendance), 0) + 1, 1), false);

alter table lineups     alter column id drop identity;
alter table lineups     alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('lineups', 'id'), greatest(coalesce((select max(id) from lineups), 0) + 1, 1), false);

alter table cotisations alter column id drop identity;
alter table cotisations alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('cotisations', 'id'), greatest(coalesce((select max(id) from cotisations), 0) + 1, 1), false);

alter table expenses    alter column id drop identity;
alter table expenses    alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('expenses', 'id'), greatest(coalesce((select max(id) from expenses), 0) + 1, 1), false);

alter table evaluations alter column id drop identity;
alter table evaluations alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('evaluations', 'id'), greatest(coalesce((select max(id) from evaluations), 0) + 1, 1), false);

-- `clubs` also needs BY DEFAULT ids (same reason as above). `coach_profiles.id`
-- is the coach's auth user id and is never auto-generated, so it is skipped.
alter table clubs alter column id drop identity;
alter table clubs alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('clubs', 'id'), greatest(coalesce((select max(id) from clubs), 0) + 1, 1), false);

-- Teams created before clubs existed have club_id = NULL. The app assigns them
-- to a default club on first load; to do it by hand instead:
--
--   insert into clubs (name, owner_id)
--   select 'ناديي', '<your-auth-uid>' where not exists (select 1 from clubs);
--   update teams set club_id = (select min(id) from clubs) where club_id is null;
